[package]
name = "kvm-switch-daemon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4"
simplelog = "0.12"
clap = { version = "4.6.1", features = ["derive"] }
kvm_core = { path = "../kvm_core" }
trigger = { path = "../trigger" }
ddc-backend = { path = "../ddc-backend" }
power-fallback = { path = "../power-fallback" }

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["wincon"] }
